-- pro_pr_post 개발자 자기소개 포스팅 데이터 삽입

INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('1', '1', '안녕하세요 :）홈페이지 제작전문기업입니다.', '자사는 오픈소스를 이용해 홈페이지가 제작되며, 고객의 요구에 맞는 커스터마이징 개발이 가능합니다! \\n 전문 기획팀 4명 / 디자인팀4명 / 퍼블리싱팀 6명/ 개발팀2명으로 구성된 웹개발 전문에이전시로 국내 최고대학 S대학교와 함께 프로젝트를 진행중에 있을만큼 디자인 / 기술력에 있어서 만큼은 최고라고 자부합니다. \\n 클라이언트의 요구에 맞게 거품없는 홈페이지 제작, 보여드리겠습니다. 감사합니다 : )', 'https://github.com/remoplus');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('2', '2', '젊고 경험많은 개발자들로 구성된 개발 팀입니다.', '아래와 같은 문의는 받지 않으니 양해 부탁드립니다. \\n- 게임 매크로 또는 핵 \\n-대한민국 형법에 어긋나는 업종 관련(예: 토토 등)\\n 저작권법에 위배되는 프로그램 (예: 멜론 무료스트리밍 등)', 'https://github.com/edoubleK');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('3', '3', '안녕하십니까? 홈페이지 제작전문기업입니다.', '자사는 오픈솔루션인 그누보드(영카트)로 홈페이지가 제작되어 고객의 요구에 맞은 커스터마이징 개발 및 제작이 가능합니다! \\n자사에서 만드는 홈페이지는 다릅니다.타업체와 차별화된 개발능력과 디자인으로 최상의 결과물을 만나보세요. \\n현재 다양한 업종을 제작한 경력 (600여개)이 있으며 대한민국 최고의 S그룹의 협력업체로 선정되어 활동중입니다.\\n거품없는 홈페이지 제작, 보여드리겠습니다.', 'https://github.com/creati-on');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('4', '4', '안녕하세요 ! 고객님의 사업을 함께 시작하는 바른기획입니다. ', '제 사업이라 생각하고 고객님의 입장에서 생각하고 소중한 인연으로 생각하겠습니다.', 'https://github.com/barun');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('5', '5', '10년이상의 개발경력과 팀리더 경력을 가지고 있는 모바일 및 웹 개발팀장입니다.', '앱과 웹사이트의 기획부터 디자인 및 퍼블리싱, 개발, 출시 및 마케팅까지 많은 분야에서 필요한 경험과 자산들을 보유하고 있으며 문제해결과 협업에 능숙한 개발자팀을 이끌고 있습니다.\\n고객님들이 요구하시는 내용들을 정확히 이해하고 고객님들과 함께 고민하고 끝까지 책임지는 마음으로 항상 최선을 다하고 있습니다.', 'https://github.com/InLight');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('6', '6', 'IOS+Android 어플 제작해드립니다.', '제공된 앱의 화면은 아이폰,아이패드,안드로이드 모두  정확하게 일치합니다.\\n모든 스타일의 앱을 만들어 드립니다.\\n\\n- 아이폰/안드로이드 네이티브 및 하이브리드 웹앱 제작 및  마켓에 무료로 배포해 드립니다.\\n- 개발완료후 개발된 제품에서 발생하는 모든 오류는 무료로 서비스해드립니다.\\n\\n메시지 주시면 빠른 시일 내에 상담 드리겠습니다. \\n고객만족 100%를 위해 노력하겠습니다.', 'https://github.com/appmaker');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('7', '7', '트렌디한 웹앱 개발', '- 웹/앱 UI, UX 기획\\n- IT전문 스타트업 7년차 팀, 복잡한 DB 구축 및 웹 서비스 개발\\n- HTML, CSS, JAVASCRIPT, JQuery, PHP 등 하드 코딩 반응형 모바일/PC 웹 사이트 제작\\n- 그누보드 등의 프레임웍을 이용한 신속한 웹사이트 제작\\n- iOS/AOS 앱패키징 및 스토어 등록 대행 서비스\\n- 무료 호스팅 연결 / 클라우드 서버 구축 서비스\\n- SSL(https) 인증 서비스', 'https://github.com/trendywebapp');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('8', '8', '안녕하세요!!  저희는 기획자 디자이너 개발자로 이루어진 스타트업입니다!', '플러터를 이용하여 크로스플랫폼 어플리케이션을 제작해드립니다.\\n\\nFlutter를 이용하면, 추가비용 없이 안드로이드와 iOS개발이 가능합니다\\n\\n예창/초창 분들을 위한 MVP모델 뿐만 아니라\\n빠른시장 검증을 위한 앱을 시간, 비용적으로 효율성 있게 진행해 드립니다.', 'https://github.com/modooapp');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('9', '9', '스타트업 대상\\n php, javascript, mysql, react native,next.js \\n웹/앱 플랫폼 개발회사입니다.', '크롤링, gps, SEO, 온라인결제 기능이 들어간 웹솔루션 및 CMS사이트 풀스택 개발진행\\n 20 예창패선정\\n 23 서울청창사\\n\\n최근에는 음성리뷰플랫폼,식자재발주견적플랫폼등\\n주요 플랫폼개발을 진행했습니다.\\n\\n개발자에게 가장 필요한건 클라이언트와의 원할한 커뮤니케이션이라고 생각합니다.\\n언제든지 성실하게 상담해드리겠습니다.', 'https://github.com/dataheros');
INSERT INTO `linkpro`.`pro_pr_post` (`pr_post_id`, `pr_pro_id`, `pr_title`, `pr_contents`, `pr_github`) VALUES ('10', '10', '\"우리가 개발하는 건 당신의 꿈\"', '개발자, 기획자, 디자이너 등 각 분야 전문가가  똘똘 뭉친 개발팀 케이플이에요.\\n차원이 다른 결과물로 당신의 반짝거리는 꿈을  현실로 만들어 드려요.\\n\\n Dream with KAYPLE.', 'https://github.com/kayple');
