-- pro 테이블 데이터 삽입
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('1', '김레모', 'remoplus', 'remoplus@gmail.com', '1111', '010-1111-1111', '7', 'N', '경북', '1', '95', '4.8', '950000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('2', '박더블', 'edoubleK', 'edoubleK@gmail.com', '2222', '010-2222-2222', '16', 'N', '인천', '2', '34', '5.0', '340000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('3', '이크리', 'creati-on', 'creati-on@naver.com', '3333', '010-3333-3333', '11', 'N', '경기 남부', '3', '155', '5.0', '1550000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('4', '김바른', 'barun', 'barun@kakao.com', '4444', '010-4444-4444', '16', 'Y', '서울', '4', '611', '4.9', '6110000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('5', '정인라', 'InLight', 'inlight@naver.com', '5555', '010-5555-5555', '12', 'N', '세종', '5', '45', '5.0', '450000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('6', '유앱메', 'appmaker', 'appmaker@app.com', '6666', '010-6666-6666', '13', 'N', '경기 남부', '6', '205', '4.9', '2050000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('7', '김트렌', 'trendywebapp', 'trendy@gmail.com', '7777', '010-7777-7777', '9', 'N', '인천', '7', '182', '4.9', '1820000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('8', '최모두', 'modooapp', 'modoo@kakao.com', '8888', '010-8888-8888', '5', 'N', '서울', '8', '3', '5.0', '30000', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('9', '황데이터', 'dataheros', 'dataheros@naver.com', '9999', '010-9999-9999', '8', 'Y', '서울', '9', '0', '0.0', '0', 'N');
INSERT INTO `linkpro`.`pro` (`pro_id`, `pro_name`, `pro_nickname`, `pro_email`, `pro_pw`, `pro_tel`, `pro_career_exp`, `pro_reside_YN`, `pro_region`, `pro_pr_id`, `pro_total_sales`, `pro_score`, `pro_cash`, `pro_del_YN`) VALUES ('10', '김케이플', 'kayple', 'kayple@gmail.com', '1010', '010-1010-1010', '12', 'N', '서울', '10', '7', '5.0', '70000', 'N');